### ISSUE TITLE
Flickering of tray-icon on i3 with Polybar

### ISSUE THREAD

**Issue by PapaBones** [terroo/wallset#11]
The video I tried this with:
https://files.catbox.moe/ku6o7s.mp4
And how it looked on my desktop.
https://files.catbox.moe/gso6w3.mp4
I use i3 on Archlinux, Kernel 5.8.5
glxinfo | grep "OpenGL version" gives me
`OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.1.6 `
in case that might have been an issue(I use an AMD card). 
I also noticed issues with drag and drop(it leaving behind black lines/boxes for a short while after moving something).

**Comment by terroo** [comment]
Scheduled as improvement for the next version
