### ISSUE TITLE
Precisa instalar o:

### ISSUE THREAD

**Issue by L1742102204** [terroo/wallset#12]
root@L174210220:/home/l1742102204/wallset.clone# sed -i 's/\"ffmpeg\" //' install.sh
root@L174210220:/home/l1742102204/wallset.clone# ./install.sh
Precisa instalar o: 'feh'
root@L174210220:/home/l1742102204/wallset.clone# apt-get install feh
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
feh is already the newest version (3.4.1-1).
0 pacotes atualizados, 0 pacotes novos instalados, 0 a serem removidos e 0 não atualizados.
root@L174210220:/home/l1742102204/wallset.clone# sed -i 's/\"feh\" //' install.sh
root@L174210220:/home/l1742102204/wallset.clone# ./install.sh
Precisa instalar o: 'imagemagick'
root@L174210220:/home/l1742102204/wallset.clone# sed -i 's/\"imagemagick\" //' install.sh
root@L174210220:/home/l1742102204/wallset.clone# ./install.sh
Precisa instalar o: 'imagemagick'
root@L174210220:/home/l1742102204/wallset.clone# apt-get install imagemagick
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
imagemagick is already the newest version (8:6.9.11.24+dfsg-1+b1).
0 pacotes atualizados, 0 pacotes novos instalados, 0 a serem removidos e 0 não atualizados.

Acho que pelo codigo, deu para você entender o que está rolando, certo?
Pelo que vi não é somente eu com o mesmo problema.
Muito legal a ideia, de verdade.
Mas se é algo para o público, tem que fazer funcionar para a maioria... Da uma ajudinha aí?

**Comment by sd33m** [comment]
same issue, but instead of imagemagick it's ffmpeg that it doesn't detect

**Comment by terroo** [comment]
Added the `--force` parameter. See the README for more details:
```sh
sudo sh install.sh --force
```
