### ISSUE TITLE
Invalid format with mp4 

### ISSUE THREAD

**Issue by legendofmiracles** [terroo/wallset#13]
I downloaded a video from reddit as a gif, then i converted it to .mp4 and when i try to run wallset with it, it always returns invalid format.
Also, if i specify another video, it doesn't output anything, and also doesn't exit, it just runs in the terminal, but my background doesn't change.

**Comment by terroo** [comment]
Please inform me the output that appeared, so that we can add to the header of valid formats. Even though MP4, headers can vary

**Comment by alx365** [comment]
```
❯ wallset -V \'At\ the\ edge,\ alone,\ and\ burning.\'-hxwjmjbmtbp51.mp4
Invalid format.
```
Thats the entire output, the video plays fine with ffmpeg.

**Comment by fkopietz** [comment]
@legendofmiracles: Rename the video file so it does not contain any whitespace characters.

**Comment by BrianRuizy** [comment]
> @legendofmiracles: Rename the video file so it does not contain any whitespace characters.

this helped me!

**Comment by ITS-ME-IZY** [comment]
> @legendofmiracles: Rename the video file so it does not contain any whitespace characters.

it doesnt work

**Comment by svistok04** [comment]
same, still won't work for me too.

**Comment by Si-kaR** [comment]
[griphen@fedora ~]$ wallset -V /home/griphen/Pictures/Wallpapers/LIVE/140111.mp4
Preparing the video......
[griphen@fedora ~]$ 



Above is my trial in the terminal. It spits "Preparing the video..."
and that's it. Nothing happens. 


Now I switch tabs to focus on some other stuff only to find this in my terminal  😂😂







X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x1800001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x800001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x2600001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x2a00001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x3800001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x3c00001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x3800001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x3800001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x4600001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x4800001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x4e00001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x5200001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x800001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x5800001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x6600001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x800001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x6800001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x7600001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x7e00001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x8c00001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x8800001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x9000001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x9200001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0xa000001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0xa200001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x1d600001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x1e600001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x15600001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x1ee00001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x15600001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x15600001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x1f800001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x1f400001
  Serial number of failed request:  16
  Current serial number in output stream:  23
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x1fa00001
  Serial number of failed request:  16
  Current serial number in output stream:  23
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
Maximum number of clients reachedfeh ERROR: Can't reopen X display.
