### ISSUE TITLE
The install bash script is broken 

### ISSUE THREAD

**Issue by rustombhesania** [terroo/wallset#14]
im using pop os 20.04

(base) rben10@pop-os:~$ cd down-wallset
(base) rben10@pop-os:~/down-wallset$ sudo sh install.sh 
[sudo] password for rben10: 
install.sh: 5: Syntax error: "(" unexpected (expecting "fi")

**Comment by Krafting** [comment]
use:
./install.sh 
or: 
sudo bash install.sh

**Comment by terroo** [comment]
Added the `--force` parameter. See the README for more details:
```sh
sudo sh install.sh --force
```
