### ISSUE TITLE
You need to install: 'ffmpeg'

### ISSUE THREAD

**Issue by lamine2000** [terroo/wallset#15]
Hello, when i try executing the installation .sh file  (<code>./install.sh</code>), it says that i need to install 'ffmpeg' but i already have it installed (i confirmed it with <code>apt-cache policy ffmpeg</code>). I tried to install the snap for ffmpeg (<code>snap install ffmpeg</code>) but the error message was still here. So i opened the installation file to try to bypass the dependencies verification step...so i executed this command : <code>su root -c "cp wallset /usr/local/bin/ && chmod +x /usr/local/bin/wallset"</code>. The wallset command was then available...but when i try to set a video as background, i get this error "X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x19200001
  Serial number of failed request:  16
  Current serial number in output stream:  23".

**Comment by terroo** [comment]
Added the `--force` parameter. See the README for more details:
```sh
sudo sh install.sh --force
```

**Comment by Mauratay** [comment]
In my case that errored out:
```sudo sh install.sh --force
install.sh: 5: Syntax error: "(" unexpected (expecting "fi")
```
I did: `./install.sh --force` instead

**Comment by milonite** [comment]
yes, it's a bash script so in case

`sudo bash install.sh --force`
