### ISSUE TITLE
sudo command in install.sh

### ISSUE THREAD

**Issue by GrbavaCigla** [terroo/wallset#2]
`sudo` should not be in install.sh. I have `doas` instead of `sudo`. Instead I should run your command like `doas ./install.sh` or in your case `sudo ./install.sh`

**Comment by terroo** [comment]
Run before to install:
sed -i 's/sudo/doas/g' install.sh

**Comment by GrbavaCigla** [comment]
I know how to fix it, I just want to let you know that this is bad practice

**Comment by terroo** [comment]
I suppose you create a version of the installer for `doas` and send a pull request

**Comment by GrbavaCigla** [comment]
https://github.com/terroo/wallset/pull/7

**Comment by GrbavaCigla** [comment]
Doesn't depend on `sudo` nor `doas`
