### ISSUE TITLE
install.sh: 5: Syntax error: "(" unexpected (expecting "fi")

### ISSUE THREAD

**Issue by hrqmonteiro** [terroo/wallset#27]
```
install.sh: 5: Syntax error: "(" unexpected (expecting "fi")
```

When trying to install. Any fix?

**Comment by hrqmonteiro** [comment]
Actually even if i run it directly using `./wallset`, it literally doesn't work. None of the commands works, either with image or with videos. Completely broken script.

**Comment by pisheeew** [comment]
I have the same problem.

**Comment by mohdfahad12328** [comment]
use `sudo bash install.sh` ,  cause in the file it was intended to use bash "#!/usr/bin/env bash"
