### ISSUE TITLE
Video framerate & quality is terrible.

### ISSUE THREAD

**Issue by reesericci** [terroo/wallset#3]
I downloaded a video, set it as a background and the framerate & quality is awful. I played the media back in a media player, and it plays fine and looks sharp.

**Comment by terroo** [comment]
Yes, this is purposeful, as not all hardware is advanced enough to be able to run high framerate rates

**Comment by reesericci** [comment]
How do I "unlock" high framerates & quality, because I have the hardware able to handle it.

**Comment by terroo** [comment]
`sed -i '/0\.01/d' $(which wallset)`

**Comment by reesericci** [comment]
That fixed my FR issue, but the quality of the video still suffers.

**Comment by reesericci** [comment]
Original quality:
![image](https://user-images.githubusercontent.com/19589006/87863885-56c65480-c926-11ea-87a9-13604d14be00.png)

Wallset quality:
![image](https://user-images.githubusercontent.com/19589006/87863876-28487980-c926-11ea-81d4-9b88ff67fdfd.png)

**Comment by barjoco** [comment]
+1 For having an option to not resize/compress the image quality and play videos at their own fps

**Comment by reesericci** [comment]
All the videos I use are borderline unusable in wallset. @terroo any fix?

**Comment by terroo** [comment]
@reesericci Scheduled for improvement. Thanks for informing

**Comment by reesericci** [comment]
any update on this @terroo ?
