### ISSUE TITLE
Installation on Debian asking for "ffmpeg" despite is being installed

### ISSUE THREAD

**Issue by JoaoGFarias** [terroo/wallset#4]
When trying to run _install.sh_ on Debian Testing the script asks for "ffmpeg", although it is installed in the system. Other programs use it as a dependency without problems.

![image](https://user-images.githubusercontent.com/1585655/87862561-c998f500-c951-11ea-81f1-cbd9f81e2cb3.png)

System info:

![image](https://user-images.githubusercontent.com/1585655/87862575-e7665a00-c951-11ea-8e02-655fb5448aae.png)

**Comment by terroo** [comment]
Debian separates packages. You probably don't have ffprobe or ffplay. In that case you will need to explicitly install:

`sudo apt install ffmpeg ffprobe ffplay`

I believe

**Comment by DGKSK8LIFE** [comment]
> sudo apt install ffmpeg ffprobe ffplay

I'm on ubuntu LTS 20; I have the same issue. That's not working for me.

**Comment by m3ofer** [comment]
i think the ffmpeg version is the problem ubuntu 20.04 LTS have 4.2.2 and the dependies is saying >=4.2.3 thats prob it manjaro and arch run it with no prob

**Comment by m3ofer** [comment]
and from the look of it you just need to run the wallset script without runing the ./install and it's going to work

**Comment by SauravDharwadkar** [comment]
Chech new pull request the changes may work , and report u still got problem or not

**Comment by terroo** [comment]
If you are sure that ffmpeg is installed, simply remove it from the installer:
```sh
sed -i 's/\"ffmpeg\" //' install.sh
```
