### ISSUE TITLE
Installation on Ubuntu asking for "ffmpeg" despite it being installed

### ISSUE THREAD

**Issue by DGKSK8LIFE** [terroo/wallset#5]

**Comment by m3ofer** [comment]
you just need to run the wallset script without runing the ./install and it's going to work

**Comment by DGKSK8LIFE** [comment]
> you just need to run the wallset script without runing the ./install and it's going to work

I think we're going to need a fix that entails the running instructions. Thanks though

**Comment by terroo** [comment]
If you are sure that ffmpeg is installed, simply remove it from the installer:
```sh
sed -i 's/\"ffmpeg\" //' install.sh
```
