### ISSUE TITLE
You gotta be kidding me. this thing is broken.

### ISSUE THREAD

**Issue by Retro-Ninja** [terroo/wallset#8]
`lavos@lavos-MS-7885:~/Documents/ImageMagick-7.0.10-24$ magick -version
Version: ImageMagick 7.0.10-24 Q16 x86_64 2020-07-24 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5) 
Delegates (built-in): freetype jbig jng jpeg lzma png tiff webp x zlib
lavos@lavos-MS-7885:~/Documents/ImageMagick-7.0.10-24$ cd ..
lavos@lavos-MS-7885:~/Documents$ cd ~/
lavos@lavos-MS-7885:~$ cd Downloads
lavos@lavos-MS-7885:~/Downloads$ cd wallset
lavos@lavos-MS-7885:~/Downloads/wallset$ ./install.sh
You need to install: 'imagemagick'
lavos@lavos-MS-7885:~/Downloads/wallset$ 
`

**Comment by PoorPocketsMcNewHold** [comment]
`~/Documents/ImageMagick-7.0.10-24`

Did you installed ImageMagick from source ?! Why didn´t you installed it from your package manager ?

**Comment by Retro-Ninja** [comment]
I've already had ImageMagick already installed, that didn't work. So I've installed it from source. That also didn't work. My system had ImageMagick by default. And still, running ./install.sh return an error saying "You need to install: 'imagemagick'. *mindblows

**Comment by m3ofer** [comment]
just run the wallset directlly ./wallset -V *.mp4

**Comment by Ohio2** [comment]
This thing indeed is broken, i cannot get it to install properly. Because it is coded badly.

**Comment by Sarthak2319** [comment]
I suggest you use Komorebi( There is a new forked version) which can do the same thing @Ohio2 @m3ofer @Retro-Ninja @PoorPocketsMcNewHold

**Comment by PoorPocketsMcNewHold** [comment]
@Sarthak2319 Those doesn’t work on Tiling windows managers, in which wallset, does work.

**Comment by terroo** [comment]
Added the `--force` parameter. See the README for more details:
```sh
sudo sh install.sh --force
```
